# -*- coding: utf-8 -*-
"""ML MODEL 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11erVn5OISfWhAtHU2lZJgN1ktqCqENvi

FIRST ML PROJECT
                  -BY AASHISH ARYA
"""

import pandas as pd

file_path="https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/NBA_2021.csv"
data=pd.read_csv(file_path,index_col="Player")
data.head()

data.shape

y=data["MP"]
data.dropna(axis=0, subset=['MP'], inplace=True)

# Select numeric columns only
numeric_cols = [cname for cname in data.columns if data[cname].dtype in ['int64', 'float64']]
X = data[numeric_cols].copy()
X.drop(['MP'], axis=1, inplace=True)
X.head()

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

X = pd.DataFrame(imputer.fit_transform(X), columns=X.columns, index=X.index)
X

y

from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

my_pipeline = Pipeline(steps=[('preprocessor', SimpleImputer()),
                              ('model', LinearRegression())])

from sklearn.model_selection import cross_val_score


scores = 1 * cross_val_score(my_pipeline,X,y,cv=5,scoring='r2')
print("MAE scores:\n", scores)

import pandas as pd

file_path="https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/NBA_2020.csv"
data_new=pd.read_csv(file_path,index_col="Player")
data_new.head()

y_new=data_new["MP"]
data_new.dropna(axis=0, subset=['MP'], inplace=True)

# Select numeric columns only
numeric_cols = [cname for cname in data_new.columns if data_new[cname].dtype in ['int64', 'float64']]
X_new = data_new[numeric_cols].copy()
X_new.drop(['MP'], axis=1, inplace=True)
X_new.head()

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

X_new = pd.DataFrame(imputer.fit_transform(X_new), columns=X_new.columns, index=X_new.index)
X_new

y_new

my_pipeline.fit(X, y)
predicted_y = my_pipeline.predict(X_new)
# print(predicted_y)

count_same = 0
for (i,j) in zip(y_new,predicted_y):
  if round(j,1)-1<=i<=round(j,1)+1:
    count_same+=1
print(count_same/651*100)

"""###Linear Regression"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,r2_score

# Function for comparing different approaches
def score_dataset1(X_train, X_test, y_train, y_test):
    model = LinearRegression()
    model.fit(X_train, y_train)
    train_preds = model.predict(X_train)
    test_preds = model.predict(X_test)
    print("MAE from LR")
    print(mean_absolute_error(y_test, test_preds))
    print("R2 score from LR")
    print(r2_score(y_test, test_preds))

"""###Random Forest

"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,r2_score

def score_dataset2(X_train, X_test, y_train, y_test):
    model = RandomForestRegressor(n_estimators=100, random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    print("MAE from RF")
    print(mean_absolute_error(y_test, preds))
    print("R2 score from RF")
    print(r2_score(y_test, preds))
    return test_preds

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np

s = (X_train.dtypes == 'object')
object_cols = list(s[s].index)

OH_encoder = OneHotEncoder(handle_unknown='ignore' )
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[object_cols]).toarray())
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_test[object_cols]).toarray())

OH_cols_train.index = X_train.index
OH_cols_valid.index = X_test.index

num_X_train = X_train.drop(object_cols, axis=1)
num_X_valid = X_test.drop(object_cols, axis=1)

OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, OH_cols_valid], axis=1)

OH_X_train.columns = OH_X_train.columns.astype(str)
OH_X_valid.columns = OH_X_valid.columns.astype(str)

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

OH_X_train_imputed = pd.DataFrame(imputer.fit_transform(OH_X_train), columns=OH_X_train.columns, index=OH_X_train.index)
OH_X_valid_imputed = pd.DataFrame(imputer.fit_transform(OH_X_valid), columns=OH_X_valid.columns, index=OH_X_valid.index)


# display(OH_X_train_imputed.head())


test_preds=score_dataset1(OH_X_train_imputed, OH_X_valid_imputed, y_train, y_test)

test_preds2=score_dataset2(OH_X_train_imputed, OH_X_valid_imputed, y_train, y_test)

# l1 = list(OH_X_train.dtypes)
# print(l1)
# print(OH_X_train.dtypes)

# Commented out IPython magic to ensure Python compatibility.
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

sns.regplot(x=y_, y=test_preds2)

sns.lineplot(data)